# Generated by Django 5.0.2 on 2024-03-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Weight', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('waste_type', models.CharField(choices=[('Bio-Degradable', 'Bio-Degradable'), ('Non_Degradable', 'Non_Degradable'), ('Hazardious-Waste', 'Hazardious-Waste')], default='Bio-Degradable', max_length=100)),
                ('ContactNumber', models.IntegerField()),
                ('State', models.CharField(max_length=100)),
                ('PinCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('dob', models.CharField(max_length=100)),
            ],
        ),
    ]
