# Generated by Django 5.0.2 on 2024-06-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_complaints_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
